// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0KlgV9XICbn9FvyubYyz2-S5zJUZ84qU',
    appId: '1:25735619387:web:d7f64e8ea3f477090f4d1e',
    messagingSenderId: '25735619387',
    projectId: 'flutter-01-4f2ab',
    authDomain: 'flutter-01-4f2ab.firebaseapp.com',
    storageBucket: 'flutter-01-4f2ab.firebasestorage.app',
    measurementId: 'G-SEY8L6NMJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAZVx1HKRIb8rlI7TJ_YnyAgxA49SNBk',
    appId: '1:25735619387:android:4c490346d6af0a320f4d1e',
    messagingSenderId: '25735619387',
    projectId: 'flutter-01-4f2ab',
    storageBucket: 'flutter-01-4f2ab.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAZVx1HKRIb8rlI7TJ_YnyAgxA49SNBk',
    appId: '1:25735619387:ios:4c490346d6af0a320f4d1e',
    messagingSenderId: '25735619387',
    projectId: 'flutter-01-4f2ab',
    storageBucket: 'flutter-01-4f2ab.firebasestorage.app',
  );
}
